### ISSUE TITLE
Unable to cast object of type 'NHibernate.Cache.CacheKey' to type 'NHibernate.Cache.QueryKey'.

### ISSUE THREAD

**Issue by javvids** [nhibernate/NHibernate-Caches#82]
**We get following error frequently since we moved from Syscache2 to CorememoryCache**

System.InvalidCastException: Unable to cast object of type 'NHibernate.Cache.CacheKey' to type 'NHibernate.Cache.QueryKey'.
   at NHibernate.Cache.QueryKey.Equals(Object other)
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at NHibernate.Caches.CoreMemoryCache.CoreMemoryCacheBase.Get(Object key)
   at NHibernate.Cache.CacheBase.GetMany(Object[] keys)
   at NHibernate.Cache.ReadWriteCache.PutMany(CacheKey[] keys, Object[] values, Int64 timestamp, Object[] versions, IComparer[] versionComparers, Boolean[] minimalPuts)
   at NHibernate.Cache.CachePutBatch.Execute(CachePutData[] data)
   at NHibernate.Cache.CacheBatcher.ExecuteBatch()
   at NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, DbDataReader reader, ISessionImplementor session, Boolean readOnly, CacheBatcher cacheBatcher)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()

**Comment by fredericDelaporte** [comment]
Can you please provide a test case reproducing the issue?
Since no contributors to my knowledge have already seen such an error, it is unlikely will will fix it without a test case.
And also check with which versions of NHIbernate.Caches and NHibernate you have the trouble

**Comment by javvids** [comment]
Version: 
NHibernate 5.2.6, 
NHibernate.Caches.CoreMemoryCache 5.6.0, 
FluentNhibernate 2.1.2

It will be difficult to provide the testcase as we dont get this error frequently.  Many times it disappears after restarting the application.  We never faced this issue with syscache2.

We are also using fluent nhibernate and we have configured cache for the entity as mentioned below
Cache.ReadWrite().Region("RegionName");
